.TH grid 1L "25 August 1993"
.SH NAME
grid \- Draw a rectilinear grid
.SH SYNOPSIS
.B "grid [deltax deltay]"
.SH DESCRIPTION
.B grid
draws on the current Mgr window a rectilinear grid,
equally spaced in x by
.B deltax
pixels, and in y by
.B
deltay
pixels.  Deltax and deltay default to a value of 10,
if not specified or if specified less than 2.
