.TH hilbert 1L "25 August 1993"
.SH NAME
hilbert \- Draw a Hilbert curve
.SH SYNOPSIS
.B "hilbert"
.SH DESCRIPTION
.B Hilbert
draws on the current Mgr window a curve
which is the 7th approximant to the Hilbert
space-filling curve.
.SH BUGS
Changing the order of the approximant
requires recompiling from source.
