#! /bin/sh

#                        Copyright (c) 1987 Bellcore
#                            All Rights Reserved
#       This document contains proprietary information that shall
#       be distributed or routed only within Bellcore and its
#       authorized clients, except with written permission of Bellcore.

# do an ls in a window
#
dir=`echo $* | sed 's./[^/]*$./.'`
(  echo "             ---> $dir <---";
   ls -CF $dir;
   echo "Hit RETURN to continue"
   ) | more

