'\"
.TH invert_colormap 1L "November 15, 1987"
.SH NAME
invert_colormap \- inverts the colormap on a SUN color display
.B MGR .
.SH SYNOPSIS
invert_colormap
.SH DESCRIPTION
.B Set_colormap
inverts the current color map in the sense of a photographic negative.
.SH SEE ALSO
set_colormap(1L)
overlay(1L)
.SH AUTHOR
S. A. Uhler
