.\"{{{}}}
.\"{{{  Title
.TH MGRSCLOCK 1 "June 20, 1993" "" "MGR Programmer's Manual"
.\"}}}
.\"{{{  Name
.SH NAME
mgrsclock \- MGR sandclock
.\"}}}
.\"{{{  Synopsis
.SH SYNOPSIS
.ad l
.B mgrsclock
.IR mm : ss
.ad b
.\"}}}
.\"{{{  Description
.SH DESCRIPTION
.B mgrsclock
is an egg timer, displaying a sand clock and counting backwards from
the time given.
.\"}}}
.\"{{{  Examples
.SH EXAMPLES
mgrsclock 05:40 # For eggs as I like them :\-)
.\"}}}
.\"{{{  Author
.SH AUTHOR
Michael Haardt
.\"}}}
.\"{{{  See also
.SH "SEE ALSO"
mgr(1)
.\"}}}
