.\"{{{}}}
.\"{{{  Title
.TH MGRSHOWFONT 1 "May 8, 1993" "" "MGR Programmer's Manual"
.\"}}}
.\"{{{  Name
.SH NAME
mgrshowfont \- browse through MGR fonts
.\"}}}
.\"{{{  Synopsis
.SH SYNOPSIS
.ad l
.B mgrshowfont
.I font ...
.ad b
.\"}}}
.\"{{{  Description
.SH DESCRIPTION
\fBmgrshowfont\fP is an interactive font browser.  It has only three
icons to control it using the right mouse button, the up arrow loads the
previous font, the down arrow loads the next font from the fonts
specified on command line.  The stop sign quits \fBmgrshowfont\fP.
.LP
Fonts can be specified as either absolute pathnames or just by their
name.
.\"}}}
.\"{{{  Diagnostics
.SH DIAGNOSTICS
If \fBmgrshowfont\fP is unable to reshape as neccesary, it will say so.
.\"}}}
.\"{{{  Author
.SH AUTHOR
Michael Haardt (u31b3hs@pool.informatik.rwth-aachen.de)
.\"}}}
.\"{{{  History
.SH HISTORY
\fBmgrshowfont\fP makes the former showfont shell script obsolete.
.\"}}}
.\"{{{  See also
.SH "SEE ALSO"
mgr(1)
.\"}}}
