.\"{{{}}}
.\"{{{  Title
.TH SQUEEZE 1 "May 9, 1993" "" "MGR Programmer's Manual"
.\"}}}
.\"{{{  Name
.SH NAME
squeeze \- compress MGR bitmap using run length encoding
.\"}}}
.\"{{{  Synopsis
.SH SYNOPSIS
.ad l
.B squeeze
.ad b
.\"}}}
.\"{{{  Description
.SH DESCRIPTION
.B squeeze
compresses MGR bitmaps using run length encoding.
.\"}}}
.\"{{{  Restrictions
.SH RESTRICTIONS
Only bitmaps in modern format can be compressed.
.\"}}}
.\"{{{  Author
.SH AUTHOR
S. A. Uhler
.\"}}}
.\"{{{  See also
.SH "SEE ALSO"
unsqueeze(1), bitmap(5)
.\"}}}
