.\"{{{  Title
.TH STARTUP 1 "May 7, 1993" "" "MGR Programmer's Manual"
.\"}}}
.\"{{{  Name
.SH NAME
startup \- produce a startup file reflecting the current mgr screen layout
.\"}}}
.\"{{{  Synopsis
.SH SYNOPSIS
.B startup
.\"}}}
.\"{{{  Description
.SH DESCRIPTION
\fBStartup\fP
prints the current \fBmgr\fP window layout on its standard output, in a
form suitable for the \fBmgr\fP startup file, usually \fB$HOME/.mgrc\fP.
.\"}}}
.\"{{{  Notes
.SH NOTES
The names of the commands running in the windows will not be printed.
.\"}}}
.\"{{{  See also
.SH "SEE ALSO"
mgr(1)
.\"}}}
