.\"{{{}}}
.\"{{{  Title
.TH UNSQUEEZE 1 "May 9, 1993" "" "MGR Programmer's Manual"
.\"}}}
.\"{{{  Name
.SH NAME
unsqueeze \- uncompress MGR bitmap using run length encoding
.\"}}}
.\"{{{  Synopsis
.SH SYNOPSIS
.ad l
.B unsqueeze
.ad b
.\"}}}
.\"{{{  Description
.SH DESCRIPTION
.B unsqueeze
uncompresses MGR bitmaps using run length encoding.
.\"}}}
.\"{{{  Author
.SH AUTHOR
S. A. Uhler
.\"}}}
.\"{{{  See also
.SH "SEE ALSO"
squeeze(1), bitmap(5)
.\"}}}
