.\"{{{}}}
.\"{{{  Title
.TH cursor 1
.\"}}}
.\"{{{  Name
.SH NAME
cursor \(em change appearance of cursor
.\"}}}
.\"{{{  Synopsis
.SH SYNOPSIS
.B cursor
.BR n | b | u | l | r | i
.\"}}}
.\"{{{  Description
.SH DESCRIPTION
.B Cursor
changes the appearance of the cursor.
.\"}}}
.\"{{{  Options
.SH OPTIONS
.IP \fBn\fP
normal
.IP \fBb\fP
box
.IP \fBu\fP
underline
.IP \fBl\fP
left 
.IP \fBr\fP
right
.IP \fBi\fP
invisible
.\"}}}
.\"{{{  See also
.SH "SEE ALSO"
mgr(1)
.\"}}}
.\"{{{  Author
.SH AUTHOR
S. A. Uhler
.\"}}}
