.\"{{{}}}
.\"{{{  Title
.TH loadfont 1
.\"}}}
.\"{{{  Name
.SH NAME
loadfont \- load font to server
.\"}}}
.\"{{{  Synopsis
.SH SYNOPSIS
.B loadfont 
.RB [ \-c ] 
.I font-name 
.I font-number
.\"}}}
.\"{{{  Description
.SH DESCRIPTION
Load the given font-name into the given font number.
.\"}}}
.\"{{{  Options
.SH OPTIONS
.IP \fB\-c\fP
Make the given font the current font.
.\"}}}
.\"{{{  See also
.SH "SEE ALSO"
mgr(1)
.\"}}}
.\"{{{  Author
.SH AUTHOR
S. A. Uhler
.\"}}}
