.\"{{{}}}
.\"{{{  Title
.TH SQUARE 1
.\"}}}
.\"{{{  Name
.SH NAME
square \- square a window
.\"}}}
.\"{{{  Synopsis
.SH SYNOPSIS
.B square
.\"}}}
.\"{{{  Description
.SH DESCRIPTION
.B Square
squares a window.
.\"}}}
.\"{{{  See also
.SH "SEE ALSO"
mgr(1)
.\"}}}
.\"{{{  Author
.SH AUTHOR
S. A. Uhler
.\"}}}
