.\"{{{}}}
.\"{{{  Title
.TH HPMGR 1 "May 3, 1993"
.\"}}}
.\"{{{  Name
.SH NAME
hpmgr \- HP 2621 Terminal emulator
.\"}}}
.\"{{{  Synopsis
.SH SYNOPSIS
.ad l
.B hpmgr
.ad b
.\"}}}
.\"{{{  Description
.SH DESCRIPTION
Hpmgr emulates a HP 2621 terminal.
.\"}}}
.\"{{{  See also
.SH "SEE ALSO"
mgr(1)
.\"}}}
