.\"{{{  Title
.TH MGRLOCK 1 "June 27, 1993"
.\"}}}
.\"{{{  Name
.SH NAME
mgrlock \- lock the console
.\"}}}
.\"{{{  Synopsis
.SH SYNOPSIS
.B mgrlock
.\"}}}
.\"{{{  Description
.SH DESCRIPTION
.B mgrlock
displays a screen-phosphor saving pattern on the console.  When
you login password is typed on standard input, the screen is restored.
If you mistype your password, the pattern direction reverses, and
you may try again.
.\"}}}
.\"{{{  Files
.SH FILES
/etc/passwd \(em to check the login password
.\"}}}
.\"{{{  Author
.SH AUTHOR
S. A. Uhler, modified by Michael Haardt
.\"}}}
.\"{{{  See also
.SH "SEE ALSO"
mgr(1)
.\"}}}
