.\"{{{}}}
.\"{{{  Title
.TH MGRMAG 1 "July 8, 1993" "" "MGR Programmer's Manual"
.\"}}}
.\"{{{  Name
.SH NAME
mgrmag \- magnify a part of the screen
.\"}}}
.\"{{{  Synopsis
.SH SYNOPSIS
.ad l
.B mgrmag
.RI [ file ]
.ad b
.\"}}}
.\"{{{  Description
.SH DESCRIPTION
.B mgrmag
magnifies a part of the screen, which can be selected using the right mouse
button.  If a filename if given,
.B mgrmag
will save the last selected bitmap in a file on exit (middle button).
.\"}}}
.\"{{{  Author
.SH AUTHOR
Michael Haardt
.\"}}}
.\"{{{  History
.SH HISTORY
.B mgrmag
replaces
.IR snap (1)
which does not exist any more.
.\"}}}
.\"{{{  See also
.SH "SEE ALSO"
mgr(1), bitmap(5)
.\"}}}
